## Python科学计算库Numpy
- NumPy的主要对象是同构多维数组。它是一个元素表（通常是数字），所有类型都相同，由非负整数元组索引。在NumPy维度中称为 轴 。

In [1]:
import numpy as np

In [14]:
array = [1,2,3,4,5]
array

[1, 2, 3, 4, 5]

In [17]:
array = np.array([1,2,3,4,5])
type(array)

numpy.ndarray

In [4]:
array2 = array + 1
array2

array([2, 3, 4, 5, 6])

In [5]:
array2 + array

array([ 3,  5,  7,  9, 11])

In [15]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [6]:
array[0]

1

In [7]:
array

array([1, 2, 3, 4, 5])

### 基础属性
- ndarray.ndim - 数组的轴（维度）的个数。在Python世界中，维度的数量被称为rank。
- ndarray.shape - 数组的维度。这是一个整数的元组，表示每个维度中数组的大小。对于有 n 行和 m 列的矩阵，shape 将是 (n,m)。因此，shape 元组的长度就是rank或维度的个数 ndim。
- ndarray.size - 数组元素的总数。这等于 shape 的元素的乘积。
- ndarray.dtype - 一个描述数组中元素类型的对象。可以使用标准的Python类型创建或指定dtype。另外NumPy提供它自己的类型。例如numpy.int32、numpy.int16和numpy.float64。
- ndarray.itemsize - 数组中每个元素的字节大小。例如，元素为 float64 类型的数组的 itemsize 为8（=64/8），而 complex32 类型的数组的 itemsize 为4（=32/8）。它等于 ndarray.dtype.itemsize 。
- ndarray.data - 该缓冲区包含数组的实际元素。通常，我们不需要使用此属性，因为我们将使用索引访问数组中的元素。

In [9]:
array.ndim

1

In [18]:
array.shape

(5,)

In [10]:
array.size

5

In [11]:
array.dtype

dtype('int64')

In [12]:
array.itemsize

8

In [13]:
array.data

#### 多维数组

In [21]:
array2 = np.array([[1,2,3], [4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
array2.shape

(2, 3)

In [22]:
array2.ndim

2