In [1]:
import numpy as np

#### 对于ndarray结构来说，里面所有的元素必须是同一类型的 如果不是的话，会自动的向下进行转换

In [39]:
gao_list = [1,2,3,4,5,6.1]
gao_array = np.array(gao_list)
gao_array

array([1. , 2. , 3. , 4. , 5. , 6.1])

### 基本属性及操作

In [6]:
type(gao_array)

numpy.ndarray

In [8]:
gao_array.dtype

dtype('float64')

In [9]:
gao_array.itemsize

8

In [11]:
gao_array.size

6

In [12]:
gao_array.shape

(6,)

In [38]:
gao_array.fill(0)
gao_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### arange(x,y,z)
- 为了创建数字组成的数组，NumPy提供了一个类似于range的函数，该函数返回数组而不是列表
- arange(x,y,z) 从x到y,每隔z个索引创建一个

In [40]:
gao_array = np.arange(0, 100, 5)
gao_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### 索引与切片

In [17]:
gao_list = [1,2,3,4,5,6]
gao_array = np.array(gao_list)
gao_array

array([1, 2, 3, 4, 5, 6])

In [18]:
gao_array[1]

2

In [19]:
gao_array[1:3]

array([2, 3])

In [20]:
gao_array[:-1]

array([1, 2, 3, 4, 5])

In [21]:
gao_array[-2:]

array([5, 6])

### 矩阵格式（多维）

In [22]:
gao_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
gao_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
gao_array.ndim

2

In [25]:
gao_array.shape

(3, 3)

In [26]:
gao_array.size

9

In [27]:
gao_array[0,2]

3

In [28]:
gao_array[1]

array([4, 5, 6])

In [29]:
gao_array[:, 1]

array([2, 5, 8])

In [30]:
gao_array[0,0:2]

array([1, 2])

### 赋值与拷贝
#### 浅拷贝

In [31]:
gao_array2 = gao_array
id(gao_array2) == id(gao_array)

True

In [32]:
gao_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
gao_array2[1,1] = 100
gao_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

#### 深拷贝

In [35]:
gao_array[1,1] = 5
gao_array2 = gao_array.copy()
gao_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
gao_array2[1,1] = 100
gao_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
gao_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

### 数据索引的方法
#### 布尔类型索引

In [47]:
bool_f = np.array([0,0,0,0,0,0,1,1,1,1], dtype=bool)
bool_f

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [43]:
data = np.arange(0, 100, 10)
data

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
data[bool_f]

array([60, 70, 80, 90])

In [49]:
random_arr = np.random.rand(10)
random_arr

array([0.55893692, 0.35263046, 0.97676241, 0.56955574, 0.96042838,
       0.56750665, 0.43918526, 0.98771053, 0.03040825, 0.28980286])

In [50]:
bool_f = random_arr > 0.5
bool_f

array([ True, False,  True,  True,  True,  True, False,  True, False,
       False])

In [53]:
random_arr[bool_f]

array([0.55893692, 0.97676241, 0.56955574, 0.96042838, 0.56750665,
       0.98771053])

In [58]:
np.where(data > 30)

(array([4, 5, 6, 7, 8, 9]),)

### 类型及类型转换

In [70]:
arr3 = np.array([1, 2, 3.5], dtype=float)
print(arr3.dtype)
print(arr3)

float64
[1.  2.  3.5]


In [74]:
arr3.astype(np.float32)

array([1. , 2. , 3.5], dtype=float32)

In [75]:
arr3

array([1. , 2. , 3.5])