## array数组的数值计算

In [1]:
import numpy as np
gao_array = np.array([[1,2,3], [4,5,6]])
gao_array

array([[1, 2, 3],
       [4, 5, 6]])

### 求和sum

In [3]:
np.sum(gao_array)

21

#### 沿着某一维度
- 可画图感受较为直观

In [7]:
np.sum(gao_array, axis=0)

array([5, 7, 9])

In [8]:
np.sum(gao_array, axis=1)

array([ 6, 15])

In [6]:
gao_array.shape

(2, 3)

### 最大值最小值

In [9]:
np.min(gao_array)

1

In [10]:
np.min(gao_array, axis=0)

array([1, 2, 3])

In [11]:
np.min(gao_array, axis=1)

array([1, 4])

In [12]:
np.max(gao_array)

6

#### 最大值最小值的索引

In [13]:
np.argmax(gao_array)

5

In [14]:
np.argmax(gao_array, axis=1)

array([2, 2])

In [15]:
np.argmax(gao_array, axis=0)

array([1, 1, 1])

### 方差
- 方差是观测值与其平均值偏差的平方的平均值
- 方差给出了数据的总体分散程度：方差越大，数据的分散程度越高。

In [19]:
gao_array.var(axis=0)

array([2.25, 2.25, 2.25])

### 标准差
- 标准差以与原始数据相同的单位表示，因此更容易直观地理解。标准差越大，表明数据点与均值的偏差越大，数据的一致性越低。

In [16]:
np.std(gao_array)

1.707825127659933

In [17]:
np.std(gao_array,axis=0)

array([1.5, 1.5, 1.5])

In [22]:
arr2=np.array([[1,1,1], [2,2,2]])
arr2.std(axis=1)

array([0., 0.])

### 切片函数（补位不满足条件的数据）
- clip(min,max)

In [23]:
arr2.clip(2)

array([[2, 2, 2],
       [2, 2, 2]])

In [26]:
gao_array.clip(3, 5)

array([[3, 3, 3],
       [4, 5, 5]])

### 四舍五入

In [29]:
arr3 = np.array([1.2,3.56,6.41])
arr3.round()

array([1., 4., 6.])

In [30]:
arr3.round(decimals=1)

array([1.2, 3.6, 6.4])