In [3]:
import numpy as np
arr1 = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
arr1

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

### 按坐标轴排序

In [2]:
arr1.sort()
arr1

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [9]:
arr1.sort(axis=0)
arr1

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [4]:
arr1.sort(axis=1)
arr1

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [8]:
arr2 = np.array([[3,2,1],[4,5,6]])
arr2.argsort()

array([[2, 1, 0],
       [0, 1, 2]])

In [9]:
arr2

array([[3, 2, 1],
       [4, 5, 6]])

In [11]:
arr3 = np.linspace(1,10,10)
arr3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 查找排序可插入的位置

In [14]:
values = [4.5, 5.5, 6.5]
np.searchsorted(arr3, values)

array([4, 5, 6])

### 优先级排序
numpy.lexsort 函数是 NumPy 库中用于进行间接排序的函数。该函数根据多个键序列对数据进行排序，返回的是一个整数索引数组，用这个索引数组对数据进行排序可以得到有序序列。排序是按照最后一个传入键的顺序来进行的，但如果遇到相同的值，则会参考前一个键。

In [16]:
arr4 = np.array([[1,0,6],
                       [1,7,0],
                       [2,3,1],
                       [2,4,0]])
arr4

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

这里最先按照第0列排序，然后是第2列，因为lexsort总是先考虑最后一个键

In [25]:
index = np.lexsort([-1*arr4[:,0],1*arr4[:,2],])
index

array([3, 1, 2, 0])

In [26]:
arr4[index]

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])