In [2]:
import numpy as np
arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr_1.shape

(10,)

In [5]:
arr_1.shape = 2,5
arr_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### reshape
reshape后元素数量必须保持一致

In [6]:
arr_1.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 增加新坐标轴

In [10]:
arr_1 = np.arange(10)
arr_1 = arr_1[np.newaxis, :]
arr_1.shape

(1, 10)

In [17]:
arr_2 = np.arange(10)
arr_2 = arr_2[:, np.newaxis,np.newaxis]
arr_2.shape

(10, 1, 1)

In [18]:
arr_2

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

### 压缩多余的坐标轴

In [20]:
arr_2 = arr_2.squeeze()
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 转置
在NumPy中，transpose 函数是用来翻转或者置换数组的轴的顺序。对于一个二维数组，transpose 会交换行和列。

In [21]:
arr_3 = np.array([[0,1,2,3,4],[5,6,7,8,9,]])
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
arr_3.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

对于多于两维的数组，您可以指定希望如何置换轴。默认情况下，transpose 函数将完全反转轴的顺序，但您也可以指定一个轴的顺序来重新排列轴

In [25]:
# 创建一个三维数组
arr_4 = np.arange(12).reshape(2, 3, 2)  # 创建一个形状为(2, 3, 2)的数组
arr_4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [27]:
# 使用 transpose 函数进行轴的自定义置换
arr_4 = np.transpose(arr_4, axes=(1, 2, 0))  # 置换轴，结果的形状将会是(2, 3, 2)
arr_4

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

### 连接

In [28]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [29]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [30]:
c = np.concatenate((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [31]:
d = np.concatenate((a,b), axis=1)
d

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [32]:
d.shape

(2, 6)

In [34]:
c = np.vstack((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [35]:
d = np.hstack((a,b))
d

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

### 拉伸

In [36]:
c.flatten()

array([ 123,  456,  678, 3214,  456,  134, 1235, 3124,  432,   43,   13,
        134])

In [37]:
d.flatten()

array([ 123,  456,  678, 1235, 3124,  432, 3214,  456,  134,   43,   13,
        134])