In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

## 构建数组

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### arange(start,end,skip)

In [5]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.arange(2,20,2, dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

#### linspace(start,end,num)

In [12]:
np.linspace(2,20,10, dtype=np.int64)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### logspace(start,end,num) 以10为底

In [27]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

#### zeros ones 快速填充矩阵

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [39]:
a = np.empty((3,3))

In [40]:
a.shape

(3, 3)

In [42]:
a.fill(9)
a

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

#### 复制同维度数组 zeros_like, ones_like

In [44]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])