In [1]:
import numpy as np

In [7]:
x = np.array([5,5])
y = np.array([3,3])

### 乘法

In [8]:
np.multiply(x,y)

array([15, 15])

In [9]:
x

array([5, 5])

In [10]:
y

array([3, 3])

### 点积

#### 向量的点积
当`dot`用于两个向量时，它计算的是这两个向量的内积（即点积）。

In [15]:
# 创建两个向量
a = np.array([1,2,3])
b = np.array([4,5,6])

# 计算点积
dot_product = np.dot(a, b)

print(dot_product) # 输出: 32 (1*4 + 2*5 + 3*6)

32


#### 矩阵与向量的乘积
当`dot`用于矩阵和向量时，它将矩阵和向量相乘，返回一个新的向量。

In [22]:
# 创建一个矩阵和一个向量
A = np.array([[1,2,3], [4,5,6]])
v = np.array([7,8,9,])
print(A.shape)
print(v.shape)

# 矩阵和向量的乘积
product = np.dot(A, v)

print(product) # 输出: [ 50 122 ]

(2, 3)
(3,)
[ 50 122]


#### 矩阵的乘积
当`dot`用于两个矩阵时，它计算的是矩阵的乘积。
给定两个矩阵A和B，其中A是一个mxn的矩阵，B是一个nxp的矩阵，则它们的乘积C将得到一个mxp的矩阵。C中的每个元素cij是通过取A的第i行和B的第j列对应元素的乘积之和的到的。

In [18]:
# 创建两个矩阵
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

# 矩阵的乘积
product = np.dot(A, B)

print(product)
# 输出:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]


### 逻辑运算

In [27]:
x = np.array([0,1,0])
y = np.array([0,1,2])

In [28]:
x == y

array([ True,  True, False])

In [30]:
np.logical_and(x,y)

array([False,  True, False])

In [31]:
np.logical_or(x,y)

array([False,  True,  True])

In [32]:
np.logical_not(x,y)

array([1, 0, 1])