In [1]:
import numpy as np

### 随机构造数组
所有生成的元素都是0-1的值

In [3]:
np.random.rand(3,2)

array([[0.25771196, 0.36799257],
       [0.30636307, 0.22427902],
       [0.25502102, 0.66835686]])

In [4]:
np.random.rand()

0.7630714821602074

In [5]:
np.random.rand(3)

array([0.51666661, 0.38310966, 0.31149733])

### 随机生成整数 randint(low,high,size,dtype)
所有生成的元素都是int，low,high左闭又开

In [12]:
np.random.randint(0,10,size=5)

array([0, 8, 6, 9, 9])

### 随机采样

In [13]:
np.random.random_sample()

0.12575980035027712

### 正态分布
在NumPy库中，`numpy.random.normal` 函数用于根据正态分布（高斯分布）生成随机数。正态分布由两个参数定义：均值（mean）和标准差（stddev），分别决定了分布的中心和宽度。

```py
numpy.random.normal(loc=0.0, scale=1.0, size=None)
```
- loc：浮点数或类浮点数，表示分布的均值（对应于分布的中心）。
- scale：浮点数或类浮点数，表示分布的标准差（对应于分布的宽度）。
- size：输出随机数的形状，可以是一个整数或整数元组。如果不提供，size 默认为None，这意味着返回单个值。

In [26]:
# 生成一个均值为 0，标准差为 0.1，形状为 (3,4) 的随机数数组
mean = 1       # 均值
std = 0.1      # 标准差
shape = (10) # 形状

random_values = np.random.normal(mean, std, shape)
# np.set_printoptions(precision=2)

print(random_values)
print(random_values.mean())

[0.96 1.03 0.76 1.04 0.99 0.85 1.01 0.96 1.04 0.93]
0.9559009093580221


### 洗牌

In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.random.shuffle(arr)
arr

array([4, 6, 5, 3, 7, 9, 2, 1, 8, 0])

### 随机种子
- 设置了随机种子之后的一次随机操作，会保持当前随机种子之后的结果
- 比如在一些战棋游戏中，无论怎么S/L得到的随机结果都一样，原因在于seed已经确定了

In [50]:
np.random.seed(100)

In [51]:
mean = 1       # 均值
std = 0.1      # 标准差
shape = (10) # 形状

random_values = np.random.normal(mean, std, shape)
random_values

array([0.83, 1.03, 1.12, 0.97, 1.1 , 1.05, 1.02, 0.89, 0.98, 1.03])