In [1]:
import numpy as np

In [4]:
%%writefile ./gao.txt
1 2 3 4 5 6
2 3 5 8 7 9

Writing ./gao.txt


### 使用py进行读取数据

In [5]:
data = []
with open('gao.txt') as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

### 使用numpy进行读取数据

In [6]:
data = np.loadtxt('gao.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [7]:
%%writefile gao2.txt
1,2,3,4,5,6
2,3,5,8,7,9


Writing gao2.txt


#### 分隔符

In [9]:
data = np.loadtxt('gao2.txt', delimiter=',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [10]:
%%writefile gao3.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,8,7,9

Writing gao3.txt


#### 忽略行

In [11]:
data = np.loadtxt('gao3.txt', delimiter=',', skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

### 使用numpy进行保存数据

In [18]:
gao_arr=np.array(([1,2,3], [4,5,6]))
gao_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.savetxt('gao4.txt', gao_arr)

In [20]:
np.savetxt('gao4.txt', gao_arr, fmt='%d')

In [21]:
np.savetxt('gao4.txt',gao_arr,fmt='%d',delimiter = ',')

In [22]:
np.savetxt('gao4.txt',gao_arr,fmt='%.2f',delimiter = ',')

### 使用numpy进行array数组结构读写

In [23]:
gao_arr = np.array([[1,2,3],[4,5,6]])
np.save('gao_arr.npy', gao_arr)

In [24]:
gao = np.load('gao_arr.npy')
gao

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
gao_arr2 = np.arange(10)
gao_arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.savez('gao.npz',a=gao_arr,b=gao_arr2)